packages:
  - webapp
  - shared
  - contracts
  - indexer

catalog:
  '@types/node': 22.18.10
  typescript: 5.8.3

patchedDependencies:
  '@nomicfoundation/hardhat-verify': patches/@nomicfoundation__hardhat-verify.patch
